openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags:
  - name: Recipes
paths:
  /api/recipes/generate:
    post:
      operationId: generateRecipe
      description: 画像と食材からレシピを生成する
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                properties:
                  success:
                    type: boolean
                    description: 処理成功フラグ
                  data:
                    allOf:
                      - $ref: '#/components/schemas/Recipe'
                    description: レスポンスデータ
                  error:
                    allOf:
                      - $ref: '#/components/schemas/ErrorInfo'
                    description: エラー情報
                description: API統一レスポンス形式
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                properties:
                  success:
                    type: boolean
                    description: 処理成功フラグ
                  error:
                    allOf:
                      - $ref: '#/components/schemas/ErrorInfo'
                    description: エラー情報
                description: API統一レスポンス形式
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                properties:
                  success:
                    type: boolean
                    description: 処理成功フラグ
                  error:
                    allOf:
                      - $ref: '#/components/schemas/ErrorInfo'
                    description: エラー情報
                description: API統一レスポンス形式
        '502':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                properties:
                  success:
                    type: boolean
                    description: 処理成功フラグ
                  error:
                    allOf:
                      - $ref: '#/components/schemas/ErrorInfo'
                    description: エラー情報
                description: API統一レスポンス形式
      tags:
        - Recipes
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                ingredients:
                  type: array
                  items:
                    type: string
                  description: 食材リスト
                images:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: 食材画像ファイル
              required:
                - ingredients
            encoding:
              ingredients:
                contentType: application/json
components:
  schemas:
    ErrorInfo:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ
      description: エラー情報
    Recipe:
      type: object
      required:
        - title
        - description
        - ingredients
        - instructions
      properties:
        title:
          type: string
          description: レシピタイトル
        description:
          type: string
          description: レシピの説明
        ingredients:
          type: array
          items:
            type: string
          description: 使用する材料リスト
        instructions:
          type: array
          items:
            type: string
          description: 調理手順
        cookingTime:
          type: integer
          format: int32
          description: 調理時間（分）
        servings:
          type: integer
          format: int32
          description: 人数分
      description: レシピ情報
servers:
  - url: http://localhost:3001
    description: Development server
    variables: {}
